

#ifndef GROUP_DESCRIPTOR_H_
#define GROUP_DESCRIPTOR_H_

#include "block.h"

#define GROUP_DESCRIPTOR unsigned char *

#define BG_GROUP_DESCRIPTOR_SIZE 0x20

#define BG_BLOCK_BITMAP_LO_OFFSET 0x00
#define BG_BLOCK_BITMAP_LO_LENGTH 0x04

#define BG_INODE_BITMAP_LO_OFFSET 0x04
#define BG_INODE_BITMAP_LO_LENGTH 0x04

#define BG_INODE_TABLE_LO_OFFSET 0x08
#define BG_INODE_TABLE_LO_LENGTH 0x04

#define BG_FREE_BLOCKS_COUNT_LO_OFFSET 0x0C
#define BG_FREE_BLOCKS_COUNT_LO_LENGTH 0x02

#define BG_FREE_INODES_COUNT_LO_OFFSET 0x0E
#define BG_FREE_INODES_COUNT_LO_LENGTH 0x02

#define BG_USED_DIRS_COUNT_LO_OFFSET 0x10
#define BG_USED_DIRS_COUNT_LO_LENGTH 0x02

#define BG_FLAGS_OFFSET 0x12
#define BG_FLAGS_LENGTH 0x02

#define BG_EXCLUDE_BITMAP_LO_OFFSET 0x14
#define BG_EXCLUDE_BITMAP_LO_LENGTH 0x04

#define BG_BLOCK_BITMAP_CSUM_LO_OFFSET 0x18
#define BG_BLOCK_BITMAP_CSUM_LO_LENGTH 0x02

#define BG_INODE_BITMAP_CSUM_LO_OFFSET 0x1A
#define BG_INODE_BITMAP_CSUM_LO_LENGTH 0x02

#define BG_ITABLE_UNUSED_LO_OFFSET 0x1C
#define BG_ITABLE_UNUSED_LO_LENGTH 0x02

#define BG_CHECKSUM_OFFSET 0x1E
#define BG_CHECKSUM_LENGTH 0x02

// 64 bit features

#define BG_BLOCK_BITMAP_HI_OFFSET 0x20
#define BG_BLOCK_BITMAP_HI_LENGTH 0x04

#define BG_INODE_BITMAP_HI_OFFSET 0x24
#define BG_INODE_BITMAP_HI_LENGTH 0x04

#define BG_INODE_TABLE_HI_OFFSET 0x28
#define BG_INODE_TABLE_HI_LENGTH 0x04

#define BG_FREE_BLOCKS_COUNT_HI_OFFSET 0x2C
#define BG_FREE_BLOCKS_COUNT_HI_LENGTH 0x02

#define BG_FREE_INODES_COUNT_HI_OFFSET 0x2E
#define BG_FREE_INODES_COUNT_HI_LENGTH 0x02

#define BG_USED_DIRS_COUNT_HI_OFFSET 0x30
#define BG_USED_DIRS_COUNT_HI_LENGTH 0x02

#define BG_ITABLE_UNUSED_HI_OFFSET 0x32
#define BG_ITABLE_UNUSED_HI_LENGTH 0x02

#define BG_EXCLUDE_BITMAP_HI_OFFSET 0x34
#define BG_EXCLUDE_BITMAP_HI_LENGTH 0x04

#define BG_BLOCK_BITMAP_CSUM_HI_OFFSET 0x38
#define BG_BLOCK_BITMAP_CSUM_HI_LENGTH 0x02

#define BG_INODE_BITMAP_CSUM_HI_OFFSET 0x3A
#define BG_INODE_BITMAP_CSUM_HI_LENGTH 0x02

#define BG_RESERVED_OFFSET 0x3C
#define BG_RESERVED_LENGTH 0x04

#endif // GROUP_DESCRIPTOR_H_
