

#ifndef GROUP_DESCRIPTOR_H_
#define GROUP_DESCRIPTOR_H_

#include "block.h"

#define GROUP_DESCRIPTOR_SIZE 0x40

#define BG_INODE_TABLE_LO_OFFSET 0x08
#define BG_INODE_TABLE_LO_LENGTH 0x04

#define BG_INODE_TABLE_HI_OFFSET 0x28
#define BG_INODE_TABLE_HI_LENGTH 0x04

#endif // GROUP_DESCRIPTOR_H_
